sonar.projectKey=backend-luckyhand
sonar.organization=skylandd
#sonar.host.url=https://sonarqube.marsx.io
#sonar.token=sqp_65c9169df5a7008627a7b99c752e75267ec4d6d0
sonar.sources=src/
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.ws.timeout=60
#sonar.tests=test

#Git Configuration
sonar.scm.provider=git
